name: Build Blog

on:
  push:
    branches:
      - main  # Set a branch to deploy

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_OWNER: fluttershub
  IMAGE_NAME: blog

jobs:
  Build_x86:
    runs-on: ubuntu-latest
    # If running with act, Uncomment below
    # container: phaze9/action-runner
    env:
      DOCKER_CONFIG: $HOME/.docker
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.IMAGE_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build_x64
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          labels: org.opencontainers.image.source https://github.com/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:x64-latest
          
  Build_ARM64:
    runs-on: [self-hosted, linux, ARM64]
    # If running with act, Uncomment below
    # container: phaze9/action-runner
    env:
      DOCKER_CONFIG: $HOME/.docker
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.IMAGE_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build_arm64
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64
          labels: org.opencontainers.image.source https://github.com/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:arm64-latest