name: Build Blog

on:
  push:
    branches:
      - main  # Set a branch to deploy

env:
  IMAGE_REPO: ghcr.io/hotarublaze
  IMAGE_NAME: fluttershub-blog

jobs:
  deploy:
    runs-on: ubuntu-18.04
    # If running with act, Uncomment below
    container: phaze9/action-runner
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          extended: true

      - name: Build
        run: cd src && hugo --minify --destination build/

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:latest